# Generated by Django 4.0.4 on 2022-06-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='comment',
        ),
    ]
